odom_topic: "/lio_sam/mapping/odometry"
robot_frame: "base_link"  # lboro data
# odom_topic: "robot/dlo/odom_node/odom"
# robot_frame: "robot/base_link"  # lboro data
trajectory_topic: "trajectory"
map_frame_id: "TagMap"
pathtosavelandmarkcsv: "config/afteroptimisation.csv"
pathtoloadlandmarkcsv: "config/beforeoptimisation.csv"
savetaglocation: true
usepriortagtable: false
batch_optimisation: true
total_tags: 1000
add2graph_threshold: 0.2
inactivity_threshold: 30.0
use_pole_constraints: true
pole_constraints_file: "config/pole_constraints.csv"
pole_constraint_noise: 0.1  # Standard deviation for pole constraints

# Enforcing Survey Data
path_to_survey_landmarks: "config/TotalStation_to_LIO_3D.csv"
use_survey_landmarks: false
survey_landmark_noise: 0.01  # Much tighter than regular point_noise
survey_landmark_prefix: "a"  # Only load tags starting with 'a'

# Stationary threshold
stationary_position_threshold: 0.05 # 5cm
stationary_rotation_threshold: 0.1 # 0.1radius
  
noise_models:
  odometry:  # 6 DOF: x, y, z, roll, pitch, yaw
    - 0.02   # x
    - 0.15   # y
    - 1.0    # z - even more uncertain
    - 0.5    # roll - even more uncertain
    - 0.5    # pitch - even more uncertain
    - 0.02   # yaw
  
  prior:  # 6 DOF
    - 0.15
    - 0.4
    - 1.5
    - 0.8
    - 0.8
    - 0.15
  
  bearing_range:  # 3 DOF
    - 0.15   # bearing
    - 0.5    # elevation - much higher
    - 1.0    # range
  
  point:  # 3 DOF
    - 1.2
    - 1.2
    - 2.0    # z much more uncertain

# camera_config:
#   cameras:
#     - name: lCam
#       topic: "/left/tag_detections"
#       frame: "left_cam"
#     - name: rCam
#       topic: "/right/tag_detections"
#       frame: "right_cam"

camera_config:
  cameras:
    - name: forwardLeftCam
      topic: "/forwardLeft/tag_detections"
      frame: "forwardLeft_cam"
    - name: forwardRightCam
      topic: "/forwardRight/tag_detections"
      frame: "forwardRight_cam"

# camera_config:
#   cameras:
#     - name: lCam
#       topic: "/l/tag_detections"
#       frame: "usb_cam_l"
#     - name: rCam
#       topic: "/r/tag_detections"
#       frame: "usb_cam_r"
#     - name: mCam
#       topic: "/m/tag_detections"
#       frame: "usb_cam_m"