odom_topic: "robot/dlo/odom_node/odom"
robot_frame: "robot/base_link"
trajectory_topic: "trajectory"
map_frame_id: "TagMap"
pathtosavelandmarkcsv: "config/afteroptimisation.csv"
pathtoloadlandmarkcsv: "config/beforeoptimisation.csv"
savetaglocation: true
usepriortagtable: false
batch_optimisation: true
total_tags: 1000
add2graph_threshold: 0.2
inactivity_threshold: 30.0

# Stationary threshold
stationary_position_threshold: 0.05 # 5cm
stationary_rotation_threshold: 0.1 # 0.1radius
  
noise_models:
  odometry:
    - 0.01
    - 0.1
    - 0.01
  prior:
    - 0.1
    - 0.3
    - 0.1
  bearing_range:
    - 0.1
    - 0.8
  point:
    - 1
    - 1
  loopClosureNoise:
    - 0.01
    - 0.01

use_tf_lookup: false

# Camera configuration
camera_config:
  cameras:
    - name: lCam
      topic: "/l/tag_detections"
      frame: "usb_cam_l"
      transform: [0, 0, 1.57079632679]
    - name: rCam
      topic: "/r/tag_detections"
      transform: [0, 0, -1.57079632679]
      frame: "usb_cam_r"
    - name: mCam
      topic: "/m/tag_detections"
      transform: [0.0, 0.0, 0.0]
      frame: "usb_cam_m"

