odom_topic: "/lio_sam/mapping/odometry"
robot_frame: "base_link"  # lboro data
trajectory_topic: "trajectory"
map_frame_id: "TagMap"
pathtosavelandmarkcsv: "config/afteroptimisation.csv"
pathtoloadlandmarkcsv: "config/beforeoptimisation.csv"
savetaglocation: true
usepriortagtable: false
batch_optimisation: true
total_tags: 1000
add2graph_threshold: 0.2
inactivity_threshold: 30.0

# Stationary threshold
stationary_position_threshold: 0.05 # 5cm
stationary_rotation_threshold: 0.1 # 0.1radius
  
noise_models:
  odometry:  # 6 DOF: x, y, z, roll, pitch, yaw
    - 0.02   # x
    - 0.15   # y
    - 1.0    # z - even more uncertain
    - 0.5    # roll - even more uncertain
    - 0.5    # pitch - even more uncertain
    - 0.02   # yaw
  
  prior:  # 6 DOF
    - 0.15
    - 0.4
    - 1.5
    - 0.8
    - 0.8
    - 0.15
  
  bearing_range:  # 3 DOF
    - 0.15   # bearing
    - 0.5    # elevation - much higher
    - 1.0    # range
  
  point:  # 3 DOF
    - 1.2
    - 1.2
    - 2.0    # z much more uncertain

camera_config:
  cameras:
    - name: lCam
      topic: "/left/tag_detections"
      frame: "left_cam"
    - name: rCam
      topic: "/right/tag_detections"
      frame: "right_cam"